### PR TITLE
Add turbojpeg.rs for turbojpeg bindings

### PR DESCRIPTION
**Pull request by tehprofessor**
Ahoy!

This is an attempt to expose the turbojpeg api bindings. I'm a n00b to rust so my apologies if this is grossly incomplete. I'm happy to take the next steps, some guidance would be great though.

I've included the bindings in `turbojpeg.rs` in `lib.rs`, and included the file under the existing feature flag "turbojpeg_api."

Thanks for your time.

### CODE REVIEW

**Comment by mjc** [comment]
The convention is one `-sys` crate per `links` in Cargo.toml; should this maybe be its own crate?

**Comment by kornelski** [comment]
Thanks! 

Can you share the bindgen command you've used, so that I can rebuild the ffi file when turbojpeg API changes?

**Comment by kornelski** [comment]
@mjc mozjpeg is based on libjpeg-turbo, so it's fine to include it in this crate

**Comment by lilith** [comment]
@tehprofessor Do you have the bindgen command around? I would love to see this merged.

**Pull request closed without merging**
