### PR TITLE
Add jpeg transform module

### PR DESCRIPTION
**Pull request by neslinesli93**
Hi! Thanks for the awesome library!

I wanted to perform some jpeg transforms defined in `transupp.h`, but I noticed that while the `transupp.c` module was included with the `turbojpeg_api` feature, it included too much bloat and the functions/types definitions where missing from `lib.rs`.

So I went on and generated the bindings just for `transupp.h`, using:

```
bindgen vendor/transupp.h > generated/transupp.rs
```

Admittedly, it needed a bit of tweaking, in particular:
1) Deal with `THREAD_LOCAL`, as explained in [this issue as well](https://github.com/kornelski/mozjpeg-sys/issues/21)
2) Add `#include "cdjpeg.h"` in `transupp.h`

Then I cherry-picked the transform functions (and de-duped many functions and types that were already defined in `lib.rs`) and created `transform.rs`. I decided to create a new feature, called `jpegtran`, that enables this new file and that is a requirement for the old `turbojpeg_api` that still needs some fixing.

I've been able to succesfully use this branch to perform some basic jpeg transformation tasks, following the `jpegtran.c` file

### CODE REVIEW

**Comment by kornelski** [comment]
Nice!

Can you remove layout tests from the bindgened file? The bindings are portable between 32 and 64 bit platforms, but the tests aren't.

**Comment by neslinesli93** [comment]
Sorry, missed that!

I saw that inside `lib.rs` all the layout tests are under a cfg:

```rust
#[cfg(target_pointer_width = "32")]
```

Should I go and just remove the tests, or put them under that cfg flag?

**Comment by kornelski** [comment]
Yeah, you can put them behind appropriate cfg too (make sure it matches your current platform)

**Comment by kornelski** [comment]
Thank you

**Pull request merged**
